### PR TITLE
Feature/update to openzeppelin v5

### PR DESCRIPTION
**Pull request by malteish**
This update came with several changes:
- `_beforeTokenTransfer()` is now called `_update()`
- all openzeppelin contracts throw errors instead of reverting with a message
- `PaymentSplitter` was removed, so the corresponding tests have been disabled
- updated solidity to 0.8.21 (^0.8.20 is required)

Also, [openzeppelin upgrades plugin](https://docs.openzeppelin.com/upgrades-plugins/1.x/) was added in preparation for [the next step](https://github.com/corpus-io/tokenize.it-smart-contracts/issues/207).

### CODE REVIEW

**Review by CJentzsch — CHANGES_REQUESTED** [review]
Looks good.
Let's have a final decision on how to distribute dividends before merging.

**Comment by malteish** [comment]
> I [Christoph] asked Consensys about what they think about our plans to upgrade the contracts to OZ 5.0. Here there comment:
> The team’s notes on OZ 5.0 are the following:
> - There are [breaking changes](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/CHANGELOG.md) in the update which should be carefully assessed
> - The team estimates that from a pure security perspective the update won’t bring many additional benefits.
> - The update won’t affect the audit engagement since we face these changes in multiple projects anyway. If you consider it beneficial and update before the audit, we are fine.

Here are the reasons for an against this update:
Pro:
- If we want to make the token upgradeable, then the token contracts will be very long-lived. Since one of the breaking changes in v5 is the storage structure of the upgradeable contracts, where will be no way to migrate an OZ v4 based token to an OZ v5 based version. Therefore, in order to support upcoming features, we should build on v5 now.


Con:
- ERC20Snapshot is removed in v5. It might be reintroduced later though. Also, OZ says we ["should be able to adapt ERC20Snapshot to 5.0 easily."](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4276)
- It does need some work. But that work has already been done, so no real argument here.

**Comment by ernestognw** [comment]
Hey, just provided more information about how to adapt 5.0 to an ERC20Snapshot in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4276#issuecomment-1783562402. In case it's helpful :)

**Comment by malteish** [comment]
> Hey, just provided more information about how to adapt 5.0 to an ERC20Snapshot in [OpenZeppelin/openzeppelin-contracts#4276 (comment)](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4276#issuecomment-1783562402). In case it's helpful 🙂

Thank you @ernestognw !

**Comment by malteish** [comment]
@CJentzsch and @malteish decided to stay with OZ v4.9 for the foreseeable future. 

The decision was based in part on the Snapshot removal, too. Some of the arguments were:

### 4.9 with Snapshots

- 4.9 is well established
- Snapshot exists
- only few changes necessary

### 5.0 with SnapshotVotes

- newest version for new storage layout → great for longevity
- newest version -> might come with new vulnerabilities
- changes necessary to replicate ERC20Snapshots with ERC20Votes
- new also for auditors
- +1 week work, more code to audit

**Pull request closed without merging**
